macro(set_with_default var default type docstring)
    if(NOT DEFINED ${var})
        set(${var} ${default})
    endif()
    set(${var} ${${var}} CACHE ${type} ${docstring} FORCE)
endmacro()

macro(assert_one_of var)
    if(NOT DEFINED ${var})
        message(FATAL_ERROR "Variable for assert_one_of macro should be set")
        return()
    else()
        string(FIND ";${ARGN};" ";${var};" IDX2)
        if (IDX EQUAL -1)
            message(FATAL_ERROR "'${${var}}' should be one of ${ARGN}")
            return()
        endif()
    endif()
endmacro()